### PR TITLE
Add basic configuration for running tests in travis-ci

### PR DESCRIPTION
**Pull request by maffoo**
The tests don't currently pass because some of them assume that a labrad manager and python test server are running. I'll work on cleaning that up as a next step so that we get a green build. After that, we'll also want to improve the test coverage.

### CODE REVIEW

**Comment by pomalley** [comment]
By cleaning up do you mean get travis-ci to make a manager somehow or remove the test dependencies on a manager/server?

**Comment by maffoo** [comment]
I'm thinking split up the tests to have unit tests which do not depend on external servers live in labrad/test as they currently do, and other "integration" tests that require external servers to be running live in a sibling directory (they would not be installed with the labrad package; see the layout/import rules section here: http://pytest.org/latest/goodpractises.html). I would still like those integration tests to be able to run in travis-ci, so I'm working on publishing a packaged version of the labrad manager that can be installed and run.

**Comment by DanielSank** [comment]
Is there really ever a need to have live servers in tests? Why not just feed data into the servers' stream buffers directly?

**Comment by maffoo** [comment]
Where do you get that data to feed in? Seems like you'd basically end up rewriting the server in order to generate the data itself. I'd say it's better to just get the servers running and let them talk to each other; it's the externally-visible end-to-end behavior that you really want to test, after all, not the internal details.

Of course, this is for integration tests. For unit tests I agree that you want to avoid dependencies on other services as much as possible which is why I think we need some separation between these different types of test.

**Comment by pomalley** [comment]
> it's the externally-visible end-to-end behavior that you really want to test, after all

This. Maybe there's some strange unflattening bug that only shows up when the data have actually been written to the wire, etc. etc.... stranger things have happened.

**Comment by pomalley** [comment]
OK, so it said the tests were passing, then I merged, and then the tests failed. I'm not sure what's up with that. Though I did get a nice email from travis-ci telling me it failed.

**Comment by pomalley** [comment]
I guess it's because of the 64bit change that happened in between the start of the travis-ci branch and the merge. After those changes got merged the numpy test no longer passes--so the branch passed tests, the master passed tests, but together they failed. How is one supposed to deal with this? I mean, how do we get travis-ci to run on the merged version?

**Comment by maffoo** [comment]
Ideally, we'd have people rebase before merging. That way the merge is a "fast-forward", which preserves linear history, and so the tests that get run against the pull request represent the actual state of the code that will exist post-merge. But I don't think there's a way to have github enforce that; we'd have to not use github to merge pull requests. In this case, I think we should just open an issue about the failing tests and fix it in a new commit.

**Comment by pomalley** [comment]
It makes sense to me to have people rebase before merging, but I'm not entirely sure it's worth the trouble of enforcing it. I guess my confusion is this: if the code can be "trivially" merged by Github, why doesn't the CI stuff just run on the post-merged code? (It seems like a no-brainer to me so I must be missing something.)

Another question: would it also work to merge (instead of rebase) before making a PR? I've read of some people preferring a rebase because it does basically the same thing but keeps the history nicer, but I'm curious and I don't understand the details.

And thanks for getting the CI stuff working, I think it's pretty cool.

**Comment by DanielSank** [comment]
I agree that rebasing is a good idea in principle but it causes serious pain if someone else has pulled your branch. How would you recommend managing that?

**Comment by maffoo** [comment]
@pomalley: according to travis-ci, they _do_ test the post-merge state of the world, not the tip of the pull request branch (http://docs.travis-ci.com/user/pull-requests/):
```Rather than test the commits from the branches the pull request is sent from, we test the merge between the origin and the upstream branch.```
Maybe it just happened in this case that master moved ahead after the pull request got tested by travis but before it was merged, and travis didn't rerun the tests? That might just be one little window of time in which problems can happen we have to live with. At least we'll have tests to tell us something is up :)

@DanielSank: you're right, this doesn't work at all if someone else has pulled your branch. What we've done at nest is use branch namespaces to tell which branches can or can't be merged. If I'm working on a `u/maffoo/*` personal branch, then I'm free to rebase and force push it, so if anyone else tries to pull that and work on it, they have to be aware that it might change out from under them and they may have to do some commit surgery to get their subsequent changes merged. If we want to share a branch, then we name it differently (`feature/*` or something like that) and we agree not to force push it. But then we try to keep it as short-lived as possible or at least make frequent merges from master into our branch to keep up to date and make the eventual merge back to master as painless as possible.

**Comment by DanielSank** [comment]
@maffoo: I agree with this branch strategy entirely. I was just concerned by the unqualified statement

> Ideally, we'd have people rebase before merging.

**Comment by pomalley** [comment]
Re: travis, I'm not really worried about it, there probably was some sort of timing confusion there, possibly augmented by the fact that master at the time didn't even have a .travis.yml. It seems to be very useful and in fact did catch this issue, even if it was after the merge.

**Pull request merged**
